# Introduction {#introduction}

This article employs some of the methods that arose within archaeology's contemplation of *Cultural transmission theory* to trace the development of four major Bronze Age burial traditions in Europe. The cultural-historical evolution of archaeological cultures and ethnic groups during the European Bronze Age is complex, and its reconstruction an ongoing endeavour of archaeology. Within this history of constant emergence, displacement and demise many different forms of burial traditions were practised. Most of them can be distinguished by the criteria *construction of the grave* and *treatment of the body*. Bronze Age burials are either flat graves or part of a burial mound, and they contain either untreated or cremated human remains. 

In a nutshell, the classic narrative of the development of these rites in Europe presented e.g. by @hardingEuropeanSocietiesBronze2000a (following @hauslerBestattungssittenFruhenBronzezeit1977; @hauslerGrabUndBestattungssitten1994; @hauslerTotenorientierungUndGeographischer1996) can be summarised as follows: In the early and middle Bronze Age inhumations dominated in different variations. Cremation burials in this time only occur in the Hungarian lowlands. Burial mounds are concentrated in parts of the Balkans as well as in eastern, western and northern Europe, while in central and southern Europe flat graves -- mostly burials -- predominate. In the Middle Bronze Age, barrows gained importance in Western and Central Europe. This observation is highly linked to the emergence of the *Tumulus culture* in Central Europe. In the late Bronze Age, the Urnfield period, cremation became the most common burial custom in the context of *Urnfield culture*. Harding's narrative is, even when taking into account its enormous simplification, partially misleading. Cremation, for example, was a lot more common already in the early and middle Bronze Age, though not in the context of the later Urnfield culture (e.g. in the Benelux area [@fokkensBronzeAgeLow2013] or Great-Britain [@robertsBritainIrelandBronze2013]).

How can major misconceptions like this arise and persist in European archaeology? Beyond missing data due to preservation and research history, an additional reason might be a lack of unified data repositories and universally acknowledged methods to measure the spatial and temporal distribution of cultural phenomena. Instead of directly querying archives with quantitative information, the typical process for the creation of large-scale syntheses is still to manually excerpt the literature of all relevant, local research traditions. The present article, in contrast, explores the former strategy. The first major question therefore is: Does openly available, bulk radiocarbon data allow reconstructing the main trends within the distribution of burial rites in Bronze Age Europe? This approach could set a precedent for a more reproducible and statistically sound research practice. If so, then the quantitative comparison of macroregional trends could also pave the way for an analysis of interaction intensity on a long-term continental scale: Do time series constructed from radiocarbon data enable meaningful observations concerning cultural and spatial distance?

To answer these questions, a theoretical framework is required that permits the comparison of human behaviour across spatial, temporal and cultural boundaries: The assumption that the cremation aspect of Early Bronze Age burial rituals in Britain could be related to the same aspect in Hungary hundreds of years later is not self-evident. *Cultural evolution theory* provides such a framework [@creanzaCulturalEvolutionaryTheory2017]. The spread of ideas in human populations over space and time is one of it's major topics: *Cultural transmission*.

Cultural evolution theory is at least as old as theories of biological evolution and underwent a long and versatile research history. Its beginnings are in *Evolutionism* and *Social darwinism* in the 19th and early 20th century, matured in conflict with *Cultural relativism* into *Neoevolutionism* up until the nineteen sixties and seventies [@petermannGeschichteEthnologie2004]. In the late seventies three major theoretical movements emerged: *Evolutionary psychology*, *Human behavioural ecology* and *Dual inheritance theory* [@smithThreeStylesEvolutionary2000]. The latter -- heavily popularised by Richard Dawkin's *Memetics* [@dawkinsSelfishGene1976] -- establishes the notion of culture acting as secondary heredity system in humans [@henrichDualinheritanceTheoryEvolution2007]: Just like in biological evolution, also *Social learning* might be prone to selection and mutation. Under this assumption methods of *Population genetics* could be employed within cultural anthropology to analyse the spread and development of ideas -- of course with the much faster pace of cultural exchange in mind. A lot of theoretical and quantitative research follows this line of thought: e.g. @cavalli-sforzaCulturalTransmissionEvolution1981, @boydCultureEvolutionaryProcess1985, @teltserEvolutionaryArchaeologyMethodological1995 or @obrienEvolutionaryArchaeologyTheory1996.

Archaeology has a unique perspective on Cultural evolution [@garveyCurrentPotentialRoles2018]: It is concerned with human behaviour over big areas and long timescales. It also works with solid proxies of cultural expression: material remains -- individual lost or discarded artefacts, the ruins of past architecture and all more inconspicuous by-products of living. We rightfully expect humans to learn handcraft as well as building techniques and traditions  -- both functionally meaningful and seemingly pointless -- from others close to them. The similarity of historically and spatially close material remains can, therefore, be explained as a direct result of social interaction [@lymanChronometersUnitsEarly2000; @lymanCultureHistoricalBiological2001; @lymanRiseFallCulture1997; @obrienEpistemologicalNatureArchaeological2002]. Questions of Cultural Transmission form the core of archaeology.

*Evolutionary archaeology*, the branch of archaeology that explicitly adopted the terminology of Cultural evolution theory, established an important distinction of cultural behaviour in *function* and *style* [@dunnell1978style]. Some types of human behaviour increase well-being and simplify survival, like specific hunting techniques, superior tools or sowing more fruitful crops. Without resorting to the inappropriate simplifications of Evolutionism, their diffusion can be expected to increase over time if we assume reasonable human actors. On the other hand, some behaviours are not related to survival and reproductive capacity, like e.g. ceramic decorations, traditional costume fashion or jewellery design. Despite or because their seemingly subordinate importance, these characteristics often pass through a breathtakingly fast development. They often serve archaeologists as a proxy for precise relative chronology. Dunnell postulates that the distribution and emergence of these stylistic cultural traits behave randomly on a population scale level. The stochastic processes that are at work are an important object of investigation and discussed as *Neutral Transmission* or *Stylistic variability* [@bentleyRandomDriftCulture2004; @lipoNeutralityStyleDrift2001; @neimanStylisticVariationEvolutionary1995; @porcicSimulatingCulturalTransmission2014; @porcicExploringEffectsAssemblage2015; @rogersNaturalSelectionCultural2008; @shennanCeramicStyleChange2001]. 

@neimanStylisticVariationEvolutionary1995 takes a closer look at this processes and develops a simple framework for the simulation of non-functional idea propagation. He identifies the essential phenomena *drift* (random dominance of similar traits) and *flow* (intergroup transmission) in population genetics to be also relevant for cultural traits in archaeology. Furthermore, he implements a measure of cultural distance to apply his theoretical insights to real-world data. 

The workflow suggested by Neiman is relevant to the burial rites data examined in this paper and was an important methodological inspiration: As burial traditions are ritualised behaviour and most of the time heavily linked to religious and spiritual beliefs they can be assumed to be stylistic traits. Of course in reality, beyond the distinction of @dunnell1978style, most behaviour is not unambiguously stylistic or functional. Burial rites cause costs regarding working time and material to a varying extent. This cost might have been influenced or had their effect on the human-nature relation: Pyres, for example, require a significant amount of wood and the erection of barrows much workforce. Still, it can be expected that these functional disadvantages were not critical most of the time -- at least regarding the general decision which kind of burial tradition is applied. Most probably they influence the magnitude of invested energy for a burial, just like the level of grief [@macdonaldGriefBurialAmerican2001] or the representational intentions of the burying relatives [@henrichEvolutionCostlyDisplays2009].

In the following sections I will (1) explain how radiocarbon data with relevant meta information can be transformed to macro regional time series of burial traditions, (2) explore how these timeseries compare to traditional archaeological narratives and (3) construct and contextualise cultural distances between macro regions over time in relation to spatial distance. For the latter a simulation based on the @neimanStylisticVariationEvolutionary1995 template was employed.
