# Results {#results}

Figure \ref{development_burial_type} and \ref{development_burial_construction} show the region-wise time series of trait occurrence. If we ignore all other archaeological knowledge, we can construct the following narrative from them: 

In the course of the Bronze Age in Europe there was a trend away from body burial towards cremation. Around 2200calBC cremation burials were almost unknown in Poland, southern Germany, northeastern France and northern Germany. In the northwest, in Great Britain and the Benelux area, and in the southeast, in Austria and the Czech Republic, however, there were early cremation traditions. These contexts could be discussed as areas of origin of the later omnipresent phenomenon. While cremation burials lost importance in Austria and the Czech Republic as well as in the Benelux region during the Early Bronze Age and only regained their importance in the Middle Bronze Age, their share increased steadily in England. Inhumation and cremation were balanced here for a long time. The situation was similar in southern Scandinavia, where the proportion of cremation burials was much lower until the Late Bronze Age. In Poland and northern Germany, cremation became relatively suddenly and completely established with the beginning of the Late Bronze Age. In northeastern France and northern Germany this change took place already in the Middle Bronze Age. In both contexts, inhumation continued to play an important role.

With regard to the question of grave mound construction, the picture is considerably more heterogeneous. In Austria and the Czech Republic, flat graves were the dominant form of burial until the Late Bronze Age, but mounds became more relevant from the Middle Bronze Age onwards. In Poland, flat and hill graves remained in balance until the Middle Bronze Age, when flat graves prevailed. The amount of data from southern Germany and northeastern France is extraordinarily small: If one believes the sample, then a sudden, radical change from burial in flat graves to hill graves took place in southern Germany at the beginning of the Middle Bronze Age. In northeastern France there were no flat graves in the Bronze Age. Northern Germany underwent a development from the dominance of flat graves in the Early Bronze Age, a short phase of increasing mound construction in the Middle Bronze Age followed by renewed dominance of the flat grave custom in the Late Bronze Age. A similar development can be seen in southern Scandinavia: Flat graves clearly predominated, but were increasingly -- almost completely -- replaced by hills, until burial in flat graves became more frequent again at the end of the Bronze Age. Burial mounds were dominant throughout the Benelux region, but in the Early and Late Bronze Ages flat graves also occurred to a significant extent. In England, flat graves were a short phenomenon in the Early Bronze Age, which did not recur later.

This narrative is wrong in many aspects. The following section contains a short comparison with the archaeological state of research for each region: 

`r a("Southeastern Central Europe")`^[Amount of graves in Radon-B for this region.]:
The artificial circular region *Southeastern Central Europe* comprises the eastern part of Austria (Upper Austria, Lower Austria, Styria, Burgenland), the northwest of Hungary, Western Slovakia, Moravia and large parts of Bohemia (Figure \ref{map_regions} A). The density of ^14^C data on graves in Radon-B is low -- dates are available from the various regions, but large areas are without evidence. Diachronically the amount of data is consistently low and reaches a minimum in the Middle Bronze Age. While there is a constant flow of information for the variable *burial type*, the number of graves without information on *burial construction* increases in the Late Bronze Age to such an extent that no meaningful overview can be derived.  The region intersects diverse geographical and cultural areas complicating the comparison with archaeological observations. In the southeast of Central Europe, cremation and inhumation already existed side by side in the Early Bronze Age, and the local tradition remained stable in this respect also due to the expansion of the burial mound tradition in the Middle Bronze Age -- with a slight overall increase in cremation graves. The Urnfield period brought the transition to the absolute dominance of cremation burial. The development of the *burial type* variable in the Radon-B proxy shows this development correctly. The information from ^14^C data on *burial construction* correctly traces the relevance of flat burials in the Early Bronze Age but then overemphasises them in the Middle Bronze Age compared to the construction of burial mounds. In the Late Bronze Age, burials on flat burial grounds were frequent, although burial mounds of the Tumulus Culture were also further documented. This impact does not become clear in the Radon-B data -- indeed due to the small number of dates [@lubosCzechLandsAustria2013; @markovaSlovakiaHungary2013].

`r a("Poland")`:
The region *Poland* completely covers the centre and western part of today's Poland. However, the ^14^C data from this region are almost exclusively from the voivodships of Kajuwien-Pommern, Lodsch and Lower Silesia. The amount of data is small overall, with significantly more data from the Early Bronze Age up to about 1700calBC. Almost no information is available from the Middle and Late Bronze Ages. This lack of data applies to both the *burial type* and the *burial construction* variables, the former being slightly better documented. The relative development of *burial type* approximates the *real* conditions -- i.e. according to the classical, archaeological narrative: inhumations were significantly more frequent in western Poland until the Late Bronze Age, while cremations did rarely occur before the Urnfield Period. In contrast, it misrepresents *burial construction*: burial mounds also played an important role in Middle Bronze Age Poland [@czebreszukBronzeAgePolish2013; @dabrowskiAeltereBronzezeitPolen2004].

`r a("Southern Germany")`:
The artificial district region *Southern Germany* covers Bavaria completely but also includes most of Baden-Württemberg and Thuringia as well as extensive areas in Moravia and Western Austria. No ^14^C data are available from the latter regions. The majority of the available data comes from the Upper Palatinate, Lower Bavaria and Swabia as well as (in Württemberg) the administrative district of Tübingen. For the Early Bronze Age, Radon-B preserves a remarkable amount of data from Southern Germany, but this amount decreases in the course of the Middle Bronze Age and leaves the Late Bronze Age almost without dated graves. The *burial type* variable is quite well understood -- although disproportionately much more of the early inhumations were recorded than urnfield burials. This wealth of information contrasts sharply with the situation regarding the *burial construction* variable, for which almost no information from this area is available throughout the Bronze Age. If one considers the relative development calculated from Radon-B and compares it with the archaeological literature, then a reasonable agreement can be found for *burial type*. Inhumation dominated for a long time but was then replaced by cremation from the Middle Bronze Age onwards and massively in the Late Bronze Age. The calculated proportions for *burial construction* are based on a negligibly small amount of data, but the proxy still indicates the right tendency for early and middle Bronze Age: Flat graves replaced mounds. The dataset does not allow any statements about the Late Bronze Age [@falkensteinWandelBestattungssittenHugelgraber2017; @jockenhovelGermanyBronzeAge2013].

`r a("Northeastern France")`:
*Northeastern France* comprises the French administrative regions Grand-Est and Bourgogne-Franche-Comté, the east of the German Baden-Württemberg, Rhineland-Palatinate and Saarland, as well as Luxembourg and Wallonia in Belgium. Accumulations of ^14^C data are only available from Württemberg and towards the Paris Basin. The amount of data is low overall, but very low in the early and early Middle Bronze Age. For *burial type*, after all, limited statements are possible after this time window, *burial construction*, on the other hand, must remain obscure. The prediction of the relative development of these variables is correspondingly error-prone. Still, the parallel existence of cremation and inhumation in the Early and Middle Bronze Age is correctly reflected. However, this situation already existed in the Early Bronze Age and indeed developed more nuanced than the proxy might suggest. Contrary to the derivation from the ^14^C ratios, flat graves were quite common in Northeastern France [@mordantBronzeAgeFrance2013].

`r a("Northern Germany")`:
The artificial region *Northern Germany* includes all federal states in East Germany, but also large parts of Lower Saxony and Schleswig-Holstein. The ^14^C data for this region come mainly from Saxony-Anhalt and neighbouring regions in Thuringia, Saxony and Lower Saxony. Also from the area north of Bremen some data are documented in Radon-B. The database does not contain as many dated graves from any other region as from northern Germany. Most of them date back to the Early Bronze Age, while the Middle Bronze Age from about 1800calBC to 1400calBC seems barren. Only for the Late Bronze Age, there is a significant number of data documented again. The meta information on *burial type* and *burial construction* trace this development to the same extent. Since in Northern Germany influences from all four cardinal points come together and contribute significantly to the formation of local cultural phenomena, it is difficult to estimate the overall development of the primary variables here as well. The ^14^C proxy correctly represents *burial site* insofar as inhumations dominated in the Early Bronze Age and were later on replaced by cremations especially in the North from the Middle Bronze Age onwards. In the Late Bronze Age though, cremation was more dominant than the dataset suggests. Concerning *burial construction*, the current Radon-B stock records the fundamental dominance of flat graves well but attributes more relevance to them in the Early and Middle Bronze Age than is usual in the archaeological assessment of the context [@hofmannRituelleUmgangMit2008; @jockenhovelGermanyBronzeAge2013].

`r a("Southern Scandinavia")`:
The region *Southern Scandinavia* includes all of Denmark with Jutland, Funen, Zeeland and all smaller islands as well as large parts of the east of southern Sweden, and coastal regions in Schleswig-Holstein and Mecklenburg-Western Pomerania. The ^14^C data are very well distributed across Jutland, Funen and the Swedish Skåne region. Since the Bronze Age in Scandinavia begins much later than in Central Europe and is measured by another chronological system, the diachronic developments cannot merely be compared through the tripartite structure of the Early, Middle and Late Bronze Ages. The period which is labelled Early Bronze Age in Central Europe corresponds to the Scandinavian Late Neolithic. The majority of data from Scandinavia are from the period IB onwards. In this respect, the data density for almost the entire Bronze Age is good -- also with regard to the two variables *burial type* and *burial construction*. The Late Neolithic from 2200calBC is a desideratum. If one carries out the necessary mental shift -- the Central European Middle Bronze Age corresponds to the Nordic Early Bronze Age -- and then compares the proxy of the relative grave form development with the archaeological observations, then one finds a substantial agreement: body graves were the rule in periods I and II (about 1800-1300calBC), but cremations also occurred sporadically. From period III onwards cremation burials gained the upper hand. In the Scandinavian Early Bronze Age burials in burial mounds were the absolute rule. In the Late Bronze Age, flat burial fields were added [@thraneScandinavia2013].

`r a("Benelux")`:
The Benelux region includes the Netherlands, northern Belgium and large parts of Lower Saxony and North Rhine-Westphalia. All these regions have ^14^C data on graves in Radon-B, but the data density in Belgium and the Netherlands is much higher. As in Southern Scandinavia, the Early Bronze Age is under-represented in the Benelux region as opposed to the Middle and Late Bronze Age, although in a slightly weaker form. While the information density of the *burial type* variable follows this course, *burial construction* is almost undocumented in the Late Bronze Age. As in the *Southern Germany* region, there is a serious difference between the information density of both variables. If one considers the relative development of the variables as they can be derived from the burial data in comparison to the archaeological state of research, there is both deviations as well as agreement. Here, too, the study region includes different cultural phenomena with highly different burial customs: In the north and east of the Benelux region, inhumations were the rule until the Late Bronze Age, while cremation dominated earlier south of the Meuse. The Radon-B proxy seems to overemphasise the dominance of cremation in the whole area. The relevance of burial mounds in the Early and Middle Bronze Age, on the other hand, is correctly reflected, and the mixture between mounds and flat graves in the context of urnfields, often resulting from the continued use of existing grave monuments, is also visible [@arnoldussenBronzeAgeSettlements2008; @drenthMoundsDeadFuneray2005; @lohofTraditionChangeBurial1994].

`r a("England")`:
The *England* region stretches across England up to York and Liverpool, incorporating parts of Wales and leaving out Cornwall and Devon in the southwest. It also touches a narrow coastal strip on the mainland, from which no ^14^C data are documented. The available data are concentrated in the southeast of Britain but are well distributed there. The diachronic data availability is relatively good in the early and middle Bronze Age but then decreases in the late Bronze Age. *burial type* and *burial construction* behave accordingly. The relative development derived from the ^14^C data indicates the correct trend for *burial type*: Cremation graves became more and more important during the Bronze Age, while inhumations appeared for a long time in parallel. However, the dataset emphasises the dominance of the cremation graves too much. Concerning the variables *burial construction*, the dominance of burial mounds corresponds perfectly to the archaeological narrative, but -- especially in the Late Bronze Age -- flat grave fields also occurred, which the data set wrongly excludes [@robertsBritainIrelandBronze2013].

Beyond the simple comparison of archaeological knowledge and information derived from Radon-B, Figure \ref{sed_region_matrix} shows the time series of squared euclidian distance for each region-region relationship. The majority of the curves in its upper right half for *burial type* correspond to expectations: At the beginning of the Bronze Age, inhumation is widespread throughout the study area, so the Euclidean distance at 2200calBC is small in almost every region-region relationship. Only the Benelux region, where the share of cremation is already high in the Early Bronze Age, is excluded. From the Middle Bronze Age onwards, but especially at the transition to the Late Bronze Age, the transition to the dominance of cremation took place all over Europe. The SED values increase in this period and show clear peaks or several successive maxima. This rise is a consequence of the fact that the transition process in each region as depicted in Radon-B is different and that it took place with a time lag compared to other regions. At the end of the Late Bronze Age, the average SED is approaching zero again, as burial by cremation dominates in almost all of Europe. The early and complete adoption of the cremation rite in the Benelux region, as depicted in Radon-B, clearly sets it apart from the other regions. England, on the other hand, with its slow, gradual transition from inhumation to cremation, stands out due to its consistently moderate distances to all other regions. It remains without accentuated minima and maxima. The situation for *burial construction* is more complicated, as can be seen from the plots in the bottom right corner of Figure \ref{sed_region_matrix}. The distance does not seem to follow a general trend, but a multitude of local and temporally limited phenomena. This heterogeneity is also due to how correctly or incorrectly the proxy developed from radon-B depicts developments in the real world. In the Middle Bronze Age, the Tumulus culture should bring about a fundamental reduction of the SED for almost all region-region relationships -- this effect is indeed weakly visible. 

Table \ref{tab:distanceandcorrelationtable*} shows that the distance networks of *burial type* and *burial construction* are not equivalent. There is also no significant negative correlation. The degree of agreement between two regions in the question of inhumation and cremation is therefore not suitable for predicting the similarity of developments in these regions concerning the dominance of flat or mound graves. Only for the time window at the transition to the Middle Bronze Age from 1800 to 1600calBC is the 5% significance level of the mantle test almost undercut, thus suggesting a statistically significant relationship. 

For the relationship between the SED network based on *burial type* and the spatial distance several observations result from Table \ref{tab:distanceandcorrelationtable*}: Surprisingly, cultural distance does not seem to correlate with spatial distance. A significant correlation between the distance measures only reveals itself for the Early Bronze Age time window 2000 to 1800calBC: Only in the Early Bronze Age, long before the universal switch to the Urnfield burial, large regions directly adjacent to each other tend to undergo the same developments rather than the ones further away from each other. In the Middle Bronze Age, the SED developments of the *burial type* variable undergo the peaks already observed in Figure \ref{sed_region_matrix}. The correlation between cultural and spatial distance over these peaks is low and even tilts between 1400 and 1200calBC, at the transition to the Late Bronze Age, into the negative -- although not significantly. The cultural distance between several geographically distant regions is then smaller than between several directly adjacent regions. Looking at the SED network of *burial construction* (Table \ref{tab:distanceandcorrelationtable*}), similar conclusions can be drawn as in the *burial type* context: The distance values here are larger overall, and the SED differences within the individual spatial distance classes are clearly more accentuated, but here, too, the early bronze age is by far the phase of the most substantial spatial correlation. It is only significant for the time window between 1800 and 1400calBC. There is no time period with negative mean correlation for *burial construction* cultural distance and spatial distance, but also here the correlation coefficient approaches zero in the Late Bronze Age. 

Simulation: What is to be expected in case of influence of spatial distance?
