# Discussion {#discussion}

## Time series {#time-series-discussion}

One major question asked in this paper was, *if openly available, bulk radiocarbon data does allow the reconstruction of main trends within the distribution of burial rites in Bronze Age Europe*. This is the case. The narrative in section \ref{time-series-results} is surprisingly similar to the one presented by @hardingEuropeanSocietiesBronze2000a. The following paragraphs contain a short evaluation of the time series in Figure \ref{development_burial_type} and \ref{development_burial_construction} in the light of the archaeological state of research for each region. Despite the general success of this methodological approach, unfortunately the amount and quality of data is still not sufficient for a comprehensive picture. The reasons for this lack of data quality are discussed in section \ref{data-quality-discussion}. \newline   

`r a("Southeastern Central Europe")`^[Amount of graves in Radon-B for this region.]:
The artificial circular region *Southeastern Central Europe* comprises the eastern part of Austria (Upper Austria, Lower Austria, Styria, Burgenland), the northwest of Hungary, Western Slovakia, Moravia and large parts of Bohemia (Figure \ref{map_regions} A). The density of ^14^C data on graves in Radon-B is low -- dates are available from the various regions, but large areas are without evidence. Diachronically the amount of data is consistently low and reaches a minimum in the Middle Bronze Age. While there is a constant flow of information for the variable *burial type*, the number of graves without information on *burial construction* increases in the Late Bronze Age to such an extent that no meaningful overview can be derived. The region intersects diverse geographical and cultural areas complicating the comparison with archaeological observations. In the southeast of Central Europe, cremation and inhumation already existed side by side in the Early Bronze Age, and the local tradition remained stable in this respect also due to the expansion of the burial mound tradition in the Middle Bronze Age -- with a slight overall increase in cremation graves. The Urnfield period brought the transition to the absolute dominance of cremation burial. The development of the *burial type* variable in the Radon-B proxy shows this development correctly. The information from ^14^C data on *burial construction* also correctly traces the relevance of flat burials in the Early Bronze Age but then overemphasises them in the Middle Bronze Age compared to the construction of burial mounds. In the Late Bronze Age, burials on flat burial grounds were frequent, although burial mounds of the Tumulus Culture were still present and in use. This impact does not become clear in the Radon-B data -- indeed due to the small number of dates [@lubosCzechLandsAustria2013; @markovaSlovakiaHungary2013].

`r a("Poland")`:
The region *Poland* completely covers the centre and western part of today's Poland. However, the ^14^C data from this region are almost exclusively from the voivodships of Kajuwien-Pommern, Lodsch and Lower Silesia. The amount of data is small, with significantly more data from the Early Bronze Age up to about 1700 calBC. Almost no information is available from the Middle and Late Bronze Ages. This lack of dates applies to both the *burial type* and the *burial construction* variables, the former being slightly better documented. The relative development of *burial type* approximates the *real* conditions -- i.e. according to the classical, archaeological narrative: inhumations were significantly more frequent in western Poland until the Late Bronze Age, while cremations did rarely occur before the Urnfield Period. In contrast, it misrepresents *burial construction*: burial mounds also played an important role in Middle Bronze Age Poland [@czebreszukBronzeAgePolish2013; @dabrowskiAeltereBronzezeitPolen2004].

`r a("Southern Germany")`:
The artificial region *Southern Germany* covers Bavaria but also includes most of Baden-Württemberg and Thuringia as well as extensive areas in Moravia and western Austria. No ^14^C dates are available from the latter regions, the majority of the available data comes from Upper Palatinate, Lower Bavaria and Swabia as well as (in Württemberg) the administrative district of Tübingen. For the Early Bronze Age, Radon-B preserves a remarkable amount of data from Southern Germany, but this amount decreases in the course of the Middle Bronze Age and leaves the Late Bronze Age almost without dated graves. The *burial type* variable is well understood -- although disproportionately much more of the early inhumations were recorded than Urnfield burials. This wealth of information contrasts sharply with the situation regarding the *burial construction* variable, for which almost no information from this area is available throughout the Bronze Age. If one considers the relative development calculated from Radon-B and compares it with the archaeological literature, then a reasonable agreement can be found for *burial type*. Inhumation dominated for a long time but was then replaced by cremation from the Middle Bronze Age onwards and massively in the Late Bronze Age. The calculated proportions for *burial construction* are based on a negligibly small amount of data, but the proxy still indicates the right tendency for the Early and Middle Bronze Age: Flat graves replaced mounds. The dataset does not allow any statements about the Late Bronze Age [@falkensteinWandelBestattungssittenHugelgraber2017; @jockenhovelGermanyBronzeAge2013].

`r a("Northeastern France")`:
*Northeastern France* comprises the French administrative regions Grand-Est and Bourgogne-Franche-Comté, the east of the German Baden-Württemberg, Rhineland-Palatinate and Saarland, as well as Luxembourg and Wallonia in Belgium. Accumulations of ^14^C data are only available from Württemberg and towards the Paris Basin. The amount of data is low overall, but very low in the Early and Middle Bronze Age. For *burial type* limited statements are possible after this time window, *burial construction*, on the other hand, must remain obscure. The prediction of the relative development of these variables is error-prone: The parallel existence of cremation and inhumation in the Early and Middle Bronze Age is correctly reflected, but this situation already existed in the Early Bronze Age and indeed developed more nuanced than the proxy might suggest. Contrary to the derivation from the ^14^C ratios, flat graves were quite common in Northeastern France [@mordantBronzeAgeFrance2013].

`r a("Northern Germany")`:
The artificial region *Northern Germany* includes all federal states in East Germany, but also large parts of Lower Saxony and Schleswig-Holstein. The ^14^C data for this region come mainly from Saxony-Anhalt and neighbouring regions in Thuringia, Saxony and Lower Saxony. Also from the area north of Bremen some data are documented in Radon-B. The database does not contain as many dated graves from any other region as from Northern Germany. Most of them date back to the Early Bronze Age, while the Middle Bronze Age from about 1800 to 1400 calBC seems barren. Only for the Late Bronze Age, there is a significant number of data documented again. The meta information on *burial type* and *burial construction* trace this development to the same extent. Since in Northern Germany influences from all four cardinal directions come together and contribute significantly to the formation of local cultural phenomena, it is difficult to estimate the overall development of the primary variables. The ^14^C proxy correctly represents *burial site* insofar as inhumations dominated in the Early Bronze Age and were later on replaced by cremations especially in the North from the Middle Bronze Age onwards. In the Late Bronze Age though, cremation was more dominant than the dataset suggests. Concerning *burial construction*, the current Radon-B stock records the fundamental dominance of flat graves well, but attributes more relevance to them in the Early and Middle Bronze Age than it is usual in the archaeological assessment of the context [@hofmannRituelleUmgangMit2008; @jockenhovelGermanyBronzeAge2013].

`r a("Southern Scandinavia")`:
The region *Southern Scandinavia* includes all of Denmark with Jutland, Funen, Zeeland and all smaller islands as well as large parts of East of Southern Sweden, and coastal regions in Schleswig-Holstein and Mecklenburg-Western Pomerania. The ^14^C data are very well distributed across Jutland, Funen and the Swedish Skåne region. Since the Bronze Age in Scandinavia begins later than in Central Europe and is measured by another chronological system, the diachronic developments cannot merely be compared through the tripartite structure of the Early, Middle and Late Bronze Ages. The period which is labelled Early Bronze Age in Central Europe corresponds to the Scandinavian Late Neolithic. The majority of data from Scandinavia are from the period IB onwards. In this respect, the data density for almost the entire Bronze Age is good -- also with regard to the two variables *burial type* and *burial construction*. The Late Neolithic from 2200 calBC is a desideratum. If one carries out the necessary mental shift -- the Central European Middle Bronze Age corresponds to the Nordic Early Bronze Age -- and compares the proxy of the relative grave form development with the archaeological observations, then one finds a substantial agreement: inhumations were the rule in periods I and II (about 1800-1300 calBC), but cremations also occurred sporadically. From period III onwards cremation burials gained the upper hand. In the Scandinavian Early Bronze Age burials in burial mounds dominated. In the Late Bronze Age, flat grave fields began to occur [@thraneScandinavia2013].

`r a("Benelux")`:
The Benelux region includes the Netherlands, Northern Belgium and large parts of Lower Saxony and North Rhine-Westphalia. All these regions have ^14^C data on graves in Radon-B, but the data density in Belgium and the Netherlands is much higher. As in Southern Scandinavia, the Early Bronze Age is under-represented in the Benelux region as opposed to the Middle and Late Bronze Age, although in a slightly weaker form. While the information density of the *burial type* variable follows this course, *burial construction* is almost undocumented in the Late Bronze Age. As in the *Southern Germany* region, there is a serious difference between the information density of both variables. If one considers the relative development of the variables as they can be derived from the burial data in comparison to the archaeological state of research, there is both deviation as well as agreement. Here, too, the study region includes different cultural phenomena with highly different burial customs: In the north and east of the Benelux region inhumations were the rule until the Late Bronze Age, while cremation dominated earlier south of the Meuse. The Radon-B proxy seems to overemphasise the dominance of cremation in the whole area. The relevance of burial mounds in the Early and Middle Bronze Age, on the other hand, is correctly reflected, and the mixture between mounds and flat graves in the context of urnfields, often resulting from the continued use of existing grave monuments, is also visible [@arnoldussenBronzeAgeSettlements2008; @drenthMoundsDeadFuneray2005; @lohofTraditionChangeBurial1994].

`r a("England")`:
The *England* region stretches across England up to York and Liverpool, incorporating parts of Wales and leaving out Cornwall and Devon in the Southwest. It also touches a narrow coastal strip on the mainland, from which no ^14^C data are documented. The available data are concentrated in the southeast of Britain but are well distributed there. The diachronic data availability is relatively good in the Early and Middle Bronze Age but then decreases in the Late Bronze Age. *burial type* and *burial construction* behave accordingly. The relative development derived from the ^14^C data indicates the correct trend for *burial type*: Cremation graves became more and more important during the Bronze Age, while inhumations appeared for a long time in parallel. However, the dataset emphasises the occurrence of cremation graves too much. Concerning the variables *burial construction*, the dominance of burial mounds corresponds perfectly to the archaeological narrative, but -- especially in the Late Bronze Age -- flat cemeteries also occurred, which the data set wrongly excludes [@robertsBritainIrelandBronze2013].

## Cultural distance

The second important question posed for this paper was, *if these time series constructed from radiocarbon data* (Figure \ref{development_burial_type} and \ref{development_burial_construction}) *allow further analysis concerning cultural and spatial distance*? While the idea behind the first question is rather technical -- reproducing already available information in a quantitative way -- the second one has a larger scope. A quantitative representation of an archaeological narrative should path the way for a more diverse set of methods to be applied to this data and cultural distance is an integral topic of archaeological research.

The expectation for this question was a clear correlation of the "cultural" SED distances for both variables *burial type* and *burial construction* as well in between these variables as with spatial distance. The simulation, though with this implementation and parametrisation for sure rather qualitatively than quantitatively, visualises how a high degree of interaction should translate to a significantly higher degree of cultural similarity across human populations (Figure \ref{simulation}). And as the European Bronze Age is usually depicted as a period of trade, travel and exchange [e.g. @kristiansenRiseBronzeAge2005; @sherrattWhatWouldBronzeAge1993] there was no reason to expect something else than Tobler's famous First Law of Geography: "everything is related to everything else, but near things are more related than distant things." [@toblerComputerMovieSimulating1970]. 

Against this background, the observation that there is no permanent, significant correlation either between the variables or with the spatial distance is all the more astonishing (Table \ref{tab:distanceandcorrelationtable*}). Only for small periods of time this correlation can be assumed based on the Radon-B data. The *burial construction* distance shows a higher degree of correlation with spatial distance than the *burial type* distance, which even seems to behave in an opposing manner: negative correlation. If one assumes the reconstructed timelines of cultural similarity intensity to be correct, than one has to explain a rise (between 2200 and 2000 calBC) and a decline (after 2000 calBC) of cultural-spatial-distance correlation. There are several reasons why any interpretation of this observation is difficult so far:

1. The amount, distribution and quality of the data as discussed in section \ref{data-quality-discussion} question the credibility of the cultural distance calculation. The macro regions have to be very big due to a lack of data and don't allow for a more precise picture.

2. The data used for this analysis was collected for another purpose and its application in this context requires a problematic shift in data meaning as explained in section \ref{data-meaning-discussion}.

3. All observations of cultural distance in this paper are based on only the two variables *burial type* and *burial construction*. This is by far not enough for any overarching conclusions about the general state of society in the Bronze Age.

Keeping this in mind, the surprising result is still valid and has to be explained. One interpretation might be, that the Early Bronze Age was a time of rising cultural exchange and religious homogenization, while in later periods different domains secluded themselves more strongly. The negative correlation of *burial type* in the Late Bronze Age could indicate long distance contacts that explicitly excluded certain intermediate regions of Central Europe. The rise of the Tumulus Culture in the Middle Bronze Age might have cushioned this effect for the variable *burial construction* and introduced more variability for a -- at that time -- less important aspect *burial type*. The latter may have been of subordinate relevance in the Tumulus Culture context. With the rise of the Urnfield Culture this phenomenon could have been reversed as *burial type* became an expression of something that could have been one of the first formalized religions in Europe: The spread of the Urnfield Culture was an extraordinary development in early European history and was possibly accompanied by a structured, religious dogma that could have built up around the symbolic content of cult wagons, sun barks and waterfowl [@bilicSwanChariotSolar2016; @kimmig_seevolkerbewegung_1964; @molloy_european_2018]. Of course these explanations could, if correct, only be considered on a big scale. For individual regions and sites specific ideological, social or even economic considerations might have been much more critical for the decision which burial tradition to adopt [@barrett_monumentality_1990; @fokkens_genesis_1997-1; @muller-scheesel_variabilitat_2009]. 

## Data quality {#data-quality-discussion}

The **A** sections of the figures \ref{development_burial_type} and \ref{development_burial_construction} with absolute grave numbers per region and year indicate areas and periods with a lot and others with few points of data. For some there is not enough information to make any decision about the relative dominance and for many the general relevance and accuracy of the resulting time series can be questioned. There is a variety of reasons for this. These should also be considered for future data acquisition in Radon-B and beyond.

1. The data in Radon-B depend on the projects and interests of the participating researchers: It was collected as needed for individual regions rather than systematically for all of Europe.

2. The availability of ^14^C dates for a region and period in the literature depends on whether a modern research project took place within this context. Besides the research interests of researchers and institutions, there are also political reasons why an area might be better or worse explored.

3. Different research traditions in archaeology considered ^14^C data in the past more or less essential for the reconstruction of absolute chronology. In various Metal Age contexts, ^14^C data provide inferior precision in comparison to relative chronological classifications - e.g. by fibula typology - and are therefore used only sporadically to create absolute chronological fix points. Dendrochronological dating is preferred in waterlogged deposits and whenever the necessary woods are available. ^14^C calibration curves form plateaus in some periods, which significantly limit the possible dating precision. If such an effect is known, then often no dates are commissioned at all.

4. ^14^C dating requires a small but sufficiently contextualised amount of organic finds. Due to the old wood and old water effect, short-lived sample materials such as bones of terrestrial organisms or charred cereal grains are preferred. The majority of ^14^C data for this work comes from bones and teeth. However, their preservation is subject to huge differences depending on the soil [@brockPrescreeningTechniquesIdentification2010; @gordonSoilPHBone1981; @nielsen-marshBoneDiagenesisEuropean2007]. In many mineral soil contexts no sufficiently good, dateable material is available. This situation can affect entire regions, if, for example, poor bone preservation prevails as a result of lime-deficient soils.

5. In very few regions and periods of the European Bronze Age the number of excavated graves is sufficiently big to assume that a statistically relevant sample of the burial culture of the entire population is documented. Instead, it is evident in most contexts that only the burials of certain social groups, genders or ethnic groups were recorded. The quantity and nature of the known graves cannot be representative. In this case it can be expected that further, deviant burial rituals were practised, which left no archaeologically visible remains. These rituals are invisible in the ^14^C data from Radon-B.

Concerning the primary variables *burial type* and *burial construction*, further special effects must be taken into account: The disturbance and robbery of graves was a widespread phenomenon in history and prehistory. Burial mounds were usually attacked more severely than flat graves due to their better visibility and could, therefore, be under-represented in Radon-B. In many places, they were also the subject of expeditions in the early days of archaeology at the end of the 19th and beginning of the 20th century. Of course, these excavations did not yield ^14^C-dates. Irrespective of this, it can be assumed that a large part of the burial mounds erected in the Bronze Age was destroyed by agricultural activity. Ploughing could also result in an under-representation of the archaeological findings [@hardingEuropeanSocietiesBronze2000a]. On the other hand, if a burial mound is still present, it is more readily visible and recognised by archaeologists today: Mounds are often clearly identifiable in aerial photographs or digital terrain models, while flat graves are much more difficult to identify for today's remote sensing methods. It is difficult to estimate the impact of these effects in detail, but an over-representation of mounds seems more likely than an over-representation of flat graves. The dating of cremation graves on bone remains methodically differs from the dating of inhumations because it is based on the extraction of the mineral, not the organic, fraction in the bone [@lantingDatingCrematedBones2001]. The underlying chemical method was developed later, has only been used more frequently in the past 15 years and is associated with some particular difficulties [@olsenCharacterisationBlindTesting2008; @strydonck14CDatingCremated2009]. Burnt bone is generally more susceptible to weathering than unburned bone. An under-representation of cremation graves in current data collections is, therefore, more plausible.

## Data meaning {#data-meaning-discussion}

This paper is based on ^14^C dates which were prepared for the dating of graves. There is a fundamental break between that great, theoretical archaeology, which wants to develop comprehensive narratives and only pay quantitative attention to the individual case, and the on-site research or emergency excavation, which has to dedicate a measure of respect and sometimes a lot of time to each grave. In this thesis, ^14^C data are converted into a proxy of calibrated density distributions within artificial working regions, which is completely detached from the individual context. ^14^C data on graves are used to attribute a feature to the absolute chronological context or to better describe the relative development within a site. The questions underlying the creation of a ^14^C date are therefore not equivalent to those imposed in this paper.

The superordinate, large perspective also tries to simplify and categorize the parameters associated with a single burial. Radon-B anticipated this step by providing the variables *burial type* and *burial construction* that can be reduced to three categories each. This is extremely useful on the one hand, but also questionable on the other. The respective contexts can be multifarious: similar rituals in different cultural contexts can have different meanings. For this work, it is assumed -- with reference to *Cultural Evolution Theory* -- that despite this restriction, actions such as burning the dead or burying in burial mounds can be passed on across cultural and ethnic group boundaries through imitation and teaching. To put it provocatively: cremation burial in the Hungarian Early Bronze Age is a manifestation of the same idea as cremation in the Northern Late Bronze Age. This is a working hypothesis, but may be questioned.

The meaning of the data in Radon-B is thus manipulated in at least three ways for the purpose of this work: By concentrating on the dated grave in contrast to the ^14^C date, this work detaches itself from the actual content of the database. By creating artificial time steps and investigation regions, the cultural-historical context of the grave is dissolved. By creating the relative development proxies, the individual grave loses its context. The present paper is a secondary use of Radon-B. A better dataset should be grave-related, not date-related, and should contain much more meta-information for each grave.
