# Conclusion {#conclusion}

*The main trends in the distribution of burial rites in Bronze Age Europe can be detected in bulk radiocarbon data* (Figure \ref{development_burial_type} B and \ref{development_burial_construction} B) and indeed *they allow long-term observations concerning cultural distance* (Figure \ref{sed_region_matrix}, Table \ref{tab:dacta} and Table \ref{tab:dactb} and Figure \ref{correlationtimeseries} B), although with the low amount of data currently available, *most findings should be taken with great caution* (Table \ref{tab:gprcrosstab}, Figure \ref{development_burial_type} A and \ref{development_burial_construction} A, Figure \ref{correlationtimeseries} A). In this paper sample size is effectively being ignored once proportions of burial rites are computed.

Even small amounts of radiocarbon dates can be transformed to meaningful regional time series, if they can be linked to the relevant meta information. Although only `r r("gpr size", sf_desc)` graves -- a small fraction of maybe hundreds of thousands burials that can be estimated for the European Bronze Age [@nikulkaArchaologischeDemographieMethoden2016] -- have been available for this analysis, the resulting reconstruction of general burial tradition trends in wast areas of Central, Northern and North-western Europe comes close to the one achieved by literature research. The time series can be employed for cultural distance calculation. They yield the surprising observation that cultural distance and spatial distance do not significantly correlate. Although this interpretation must be treated with caution, it seems as if the spread of burial traditions are not simple *Diffusion of Innovation* events as introduced by @rogersDiffusionInnovations1962, but the result of more complex interactions between competing ideas. 

From the point of view of Cultural complexity -- the question, which factors accelerate or decelerate the variability of human behaviour [@henrichDemographyCulturalEvolution2004; @mesoudiWhatCumulativeCultural2018; @vaesenPopulationSizeDoes2016] -- the long term dominance fluctuations of one burial rite over the other are remarkable. Its standard explanation models (among others population density and environmental risk) can hardly be applied to stylistic variables.

Future research is required to untangle these interactions -- of course on the basis of more and more precise data. In this future work the methodology should be refined and extended in several ways. Some important ideas:

1. Replacing time slices in the correlation analysis by a moving window approach to get a continuous interaction proxy time series.

2. Applying a model based analysis of the idea proportion adoption curve time series and their regional differences to get a better understanding of mutual influence, earliest uptake and laggards.

3. Comparing the real world correlation time series with ones constructed from simulated, randomly permuting observations to test the significance of seemingly positive or negative correlation.

4. Abolishing the separation into artificial regions for the cultural distance and correlation analysis in favour of an approach based on individual observations [@loogEstimatingMobilityUsing2017].

Finally it is also important to ask what this paper means for the study of human behaviour in general. Two possible answers:

1. For this paper burial traditions were the main object of research, but the same approach could be applied to reconstruct other aspects of cultural behaviour. The idea to systematically collect data points that combine spatial and temporal location with simplified meta information about cultural phenomena might be a way to achieve better reproducibility of overarching narratives. Fast and easy *reproducibility* is of crucial importance to achieve scientific progress and it includes the notion of rather technical *preproducibility* [@starkReproducibilityMustCome2018]: Data (and code) must be shared to fuel advances in anthropological theory building [@kitzesPracticeReproducibleResearch2017; @marwickComputationalReproducibilityArchaeological2017; @marwickPackagingData2018].   

2. This paper is built upon Cultural transmission and thereby Cultural evolution theory (see section \ref{introduction}). It not just relies on terminology and methodology developed in this field, the process of abstraction necessary to go from radiocarbon dates to cultural distance was also heavily influenced by Evolutionary archaeology. This theoretical framework might be a source of inspiration and methods for other projects. The adoption and adaption of statistical tools and models from population genetics into anthropology was and is a unique characteristic of Cultural Evolution theory [@cavalli-sforzaCulturalTransmissionEvolution1981; @boydCultureEvolutionaryProcess1985; @teltserEvolutionaryArchaeologyMethodological1995; @obrienEvolutionaryArchaeologyTheory1996]. On the other hand, archaeology is explicitly concerned with human behaviour over big areas and long time scales and can reciprocate with a unique perspective [@garveyCurrentPotentialRoles2018].
