# Supplementary Remarks

## Data quality {#data-quality-discussion}

The **A** sections of the figures \ref{development_burial_type} and \ref{development_burial_construction} with absolute grave numbers per region and year indicate areas and periods with a lot and others with few points of data. For some there is not enough information to make any decision about the relative dominance and for many the general relevance and accuracy of the resulting time series can be questioned. There are a variety of reasons for this. These should also be considered for future data acquisition in Radon-B and beyond.

1. The data in Radon-B depend on the projects and interests of the participating researchers: It was collected as needed for individual regions rather than systematically for all of Europe.

2. The availability of ^14^C dates for a region and period in the literature depends on whether a modern research project took place within this context. Besides the research interests of researchers and institutions, there are also political reasons why an area might be better or worse explored.

3. Different research traditions in archaeology considered ^14^C data in the past more or less essential for the reconstruction of absolute chronology. In various Metal Age contexts, ^14^C data provide inferior precision in comparison to relative chronological classifications - e.g. by fibula typology - and are therefore used only sporadically to create absolute chronological fix points. Dendrochronological dating is preferred in waterlogged deposits and whenever the necessary woods are available. ^14^C calibration curves form plateaus in some periods, which significantly limit the possible dating precision. If such an effect is known, then often no dates are commissioned at all.

4. ^14^C dating requires a small but sufficiently contextualised amount of organic finds. Due to the old wood and old water effect, short-lived sample materials such as bones of terrestrial organisms or charred cereal grains are preferred. The majority of ^14^C data for this paper comes from bones and teeth. However, their preservation is subject to huge differences depending on the soil [@brockPrescreeningTechniquesIdentification2010; @gordonSoilPHBone1981; @nielsen-marshBoneDiagenesisEuropean2007]. In many mineral soil contexts no sufficiently good, dateable material is available. This situation can affect entire regions, if, for example, poor bone preservation prevails as a result of lime-deficient soils.

5. In very few regions and periods of the European Bronze Age the number of excavated graves is sufficiently big to assume that a statistically relevant sample of the burial culture of the entire population is documented. Instead, it is evident in most contexts that only the burials of certain social groups, genders or ethnic groups were recorded. The quantity and nature of the known graves cannot be representative. In this case it can be expected that further, deviant burial rituals were practised, which left no archaeologically visible remains. These rituals are invisible in the ^14^C data from Radon-B.

Concerning the primary variables *burial type* and *burial construction*, further special effects must be taken into account: The disturbance and robbery of graves was a widespread phenomenon in history and prehistory. Burial mounds were usually attacked more severely than flat graves due to their better visibility and could, therefore, be under-represented in Radon-B. In many places, they were also the subject of expeditions in the early days of archaeology at the end of the 19th and beginning of the 20th century. Of course, these excavations did not yield ^14^C-dates. Irrespective of this, it can be assumed that a large part of the burial mounds erected in the Bronze Age was destroyed by agricultural activity. Ploughing could also result in an under-representation of the archaeological findings [@hardingEuropeanSocietiesBronze2000a]. On the other hand, if a burial mound is still present, it is more readily visible and recognised by archaeologists today: Mounds are often clearly identifiable in aerial photographs or digital terrain models, while flat graves are much more difficult to identify for today's remote sensing methods. It is difficult to estimate the impact of these effects in detail, but an over-representation of mounds seems more likely than an over-representation of flat graves. The dating of cremation graves on bone remains methodically differs from the dating of inhumations because it is based on the extraction of the mineral, not the organic, fraction in the bone [@lantingDatingCrematedBones2001]. The underlying chemical method was developed later, has only been used more frequently in the past 15 years and is associated with some particular difficulties [@olsenCharacterisationBlindTesting2008; @strydonck14CDatingCremated2009]. Burnt bone is generally more susceptible to weathering than unburned bone. An under-representation of cremation graves in current data collections is, therefore, more plausible.

## Data meaning {#data-meaning-discussion}

This paper is based on ^14^C dates which were prepared for the dating of graves. There is a fundamental break between that great, theoretical archaeology, which wants to develop comprehensive narratives and only pay quantitative attention to the individual case, and the on-site research or emergency excavation, which has to dedicate a measure of respect and sometimes a lot of time to each grave. In this paper, ^14^C data are converted into a proxy of calibrated density distributions within artificial working regions, which is completely detached from the individual context. ^14^C data on graves are used to attribute a feature to the absolute chronological context or to better describe the relative development within a site. The questions underlying the creation of a ^14^C date are therefore not equivalent to those imposed in this paper.

The superordinate, large perspective also tries to simplify and categorize the parameters associated with a single burial. Radon-B anticipated this step by providing the variables *burial type* and *burial construction* that can be reduced to three categories each. This is extremely useful on the one hand, but also questionable on the other. The respective contexts can be multifarious: similar rituals in different cultural contexts can have different meanings. For this paper, it is assumed -- with reference to *Cultural Evolution Theory* -- that despite this restriction, actions such as burning the dead or burying in burial mounds can be passed on across cultural and ethnic group boundaries through imitation and teaching. To put it provocatively: cremation burial in the Hungarian Early Bronze Age is a manifestation of the same idea as cremation in the Northern Late Bronze Age. This is a working hypothesis, but may be questioned.

The meaning of the data in Radon-B is thus manipulated in at least three ways for the purpose of this paper: By concentrating on the dated grave in contrast to the ^14^C date, it detaches itself from the actual content of the database. By creating artificial time steps and investigation regions, the cultural-historical context of the grave is dissolved. By creating the relative development proxies, the individual grave loses its context. The present paper is a secondary use of Radon-B. A better dataset should be grave-related, not date-related, and should contain much more meta-information for each grave.

