# Technical Remarks

## Acknowledgements

I would like to offer my special thanks to my supervisors PD Dr. Oliver Nakoinz (University of Kiel) and Dr. Martin Hinz (University of Bern) for developing this research idea with me and for ongoing support and advice before, while and after the creation of the master thesis this article is based on. I had helpful discussions at different stages of the research process with Dr. Jutta Kneisel, Dr. Christoph Rinne, Dr. Daniel Knitter, Dr. Nils Müller-Scheeßel and David Matzig, B.A. (all University of Kiel). Beyond these colleagues at Kiel University I am particularly grateful for the feedback, encouragement and literature recommendations by Prof. Dr. Ben Marwick (University of Washington) and the valuable C++ code review by Benny Baumann (Kiel).

Finally I would like to thank Sergi Valverde (Pompeu Fabra University Barcelona) and Simon Carrignon (Barcelona Supercomputing Center) for the organisation of the session *Evolution of Cultural Complexity III* at the Conference on Complex Systems 2018 in Thessaloniki (Greece) where this paper was initially presented. 

## Declaration of Conflicting Interests

The author declared no potential conflicts of interest with respect to the research, authorship, and/or publication of this article.

## Funding

This research received no specific grant from any funding agency in the public, commercial, or not-for-profit sectors, except for a 300Euro travel grant to attend the Conference on Complex Systems 2018 by the International Center of Kiel University.
