---
title: A radiocarbon data based evaluation of Cultural Transmission in Bronze Age burial rites of Central, Northern and North-western Europe
runninghead: Schmid.
author:
- name: Clemens Schmid
  num: 1
address:
- num: 1
  org: Römisch-Germanisches Zentralmuseum, Leibniz-Forschungsinstitut für Archäologie, Mainz, Germany
corrauth: Clemens Schmid, Römisch-Germanisches Zentralmuseum, Leibniz-Forschungsinstitut für Archäologie, D - 55116 Mainz.
email: clemens@nevrome.de
abstract: European Bronze age archaeology traditionally focusses on two major dimensions to categorise burials - although there's an immense variability of attendant phenomena within this spectrum -- Flat graves versus burial mounds and cremation versus inhumation. These traits are an indispensable ingredient for common narratives of sociocultural interaction in the Bronze age. This complex system of ideological affiliation and exchange can be described in the terms of Cultural Evolution theory. Burial rites are extraordinary cultural traits -- Following Dunnels [1] distinction between function and style based on relevance for selection, they can be handled as neutral variants. As demonstrated by Neiman [2], drift and intergroup transmission as opposed to natural selection should therefore be the decisive processes for their expansion. On the other hand funerals touch upon personal loss and profound religious beliefs -- They are not short-lived fashion and most probably well interlinked with other - many archaeologically inaccessible - traits. This paper will present the results of my currently ongoing master thesis. To study the diffusion of burial rites, I employ the dataset RADON-B [3] which contains more then two thousand Bronze age 14C dates of graves from Central, Northern and North-western Europe. Based on this information I construct regional time series that document how rituals change. For a better understanding of the real-world phenomena I implement a computational model in R and C++. It simulates the expansion of mutually exclusive ideas in an artificial population graph and provides an environment to explore the effects of parameters like group size or the degree of intergroup idea transmission.
keywords: Bronze Age, Burial Traditions, Cultural Evolution, Cultural Transmission
classoption:
  - Afour
  - times
bibliography: ../references.bib
bibliographystyle: apalike
output:
  rticles::sage_article:
    keep_tex: yes
    includes:
        in_header: preamble.tex
---

```{r echo=FALSE}
library(magrittr)

# allow easy dynamic value integration
sf_prep <- "../analysis/data/output_data/sf_prep.txt"
sf_desc <- "../analysis/data/output_data/sf_desc.txt"
r <- txtstorage::read
a <- function(x) {r("regions graves amounts", sf_prep) %>% strsplit(", ") %>% unlist %>% magrittr::extract(grepl(x, .))}
```

```{r child = '01_Introduction.Rmd'}
```

```{r child = '02_Materials_and_Methods.Rmd'}
```

```{r child = '03_Results.Rmd'}
```

```{r child = '04_Discussion.Rmd'}
```

```{r child = '05_Conclusion.Rmd'}
```

```{r child = '06_Remarks.Rmd'}
```
