language: r

cache:
  packages: yes

sudo: required

env:
  global:
    - secure: "V4IqOb6bLYmAVTVVNJdCpNJ6YOdpIUpHv4PTr0WzMMREj3zSGIOVtsGopTXKXujAvVXCWNsRC4aZnUDKs/a6doY5f4Pflpf9+19VD74D59aehZhYOQVJv02V5yTq+GxKFUvNZWYlmECvvnSTaBM9CZs8Eopw9xDkG+S1K5ZKZ6mWfuakiKQbYgxzwK6IzZw/9kjbqnK5+R3XJ+r9O+h5SPVMR/CQ02te//ytWtg+J7Qxxfh5kOh/IHSZk7Tx1YOlXQoMJoryMkRoOeyQwukr8gI4bTkligSoyvr58T4l1MeJrNxGMx1pSWGDqflvm0QfYB5E5GuAzsvHvEgdba66jLVidE87sxSFz2eKxnHDwjM/HDsq2rSEa4K5D5DaNd1iekGHnhw3K6Ebl9IFkND8xYxRzrk39oIDt7HIhy3ESChgmnaGg//DVJz8QFGTax0T01CKD708DlXG917gqdMfzyWqR09mUJIVvybfwTy/lDreumeh1gmj+uTjV331s4g6/9I+/3HtDt/x8CBJKHFVuito0dMG7vEJjerbsZzXo6kh8pQ8tXFisDVSxWyYLdUaaV46u48TEoewWQE5wralJggzOKDnZMVUBAzecRDWrBZYlCpH2Xpy0zrfP/dNKETQ1YLzA1fntppscsZNo4ryy1Fv1PRWXywd9U/0nP+f+AU="

# blocklist
branches:
  except:
  - document

addons:
  apt:
    packages:
      - pandoc-citeproc

before_script:
  - chmod +x ./_run_analysis.sh
  - chmod +x ./_render_article.sh
  - chmod +x ./_deploy_article.sh

script:
  - ./_run_analysis.sh
  - ./_render_article.sh
  - ./_deploy_article.sh

