# Introduction {#introduction}

This articles employs some of the methods that arose within archaeology's contemplation of *Cultural transmission theory* to trace the development of four major Bronze Age burial traditions in Europe. The cultural-historical evolution of archaeological cultures and ethnic groups during the European Bronze Age is complex and it's reconstruction an ongoing endeavour of archaeology. Within this history of constant emergence, displacement and demise many different forms of burial traditions were practised. Most of them can be distinguished by the criteria *burial construction* and *treatment of the body*. Bronze Age burials are either flat graves or part of a burial mound, and they contain either untreated or cremated human remains. In a nutshell, the classic narrative of the development of these rites in Europe presented e.g. by @hardingEuropeanSocietiesBronze2000a (following @hauslerBestattungssittenFruhenBronzezeit1977; @hauslerGrabUndBestattungssitten1994; @hauslerTotenorientierungUndGeographischer1996) can be summarised as follows: In the early and middle Bronze Age inhumations dominated in different variations. Cremation burials in this time only occur in the Hungarian lowlands. Burial mounds are concentrated in parts of the Balkans as well as in eastern, western and northern Europe, while in central and southern Europe flat graves -- mostly burials -- predominate. In the Middle Bronze Age, barrows gained importance in Western and Central Europe. This is highly linked to the emergence of the *Tumulus culture* in Central Europe. In the late Bronze Age, the Urnfield period, cremation became the most common burial custom in the context of *Urnfield culture*. 

Hardings narrative is, even when taking into account it's enormous simplification, partially misleading. Cremation, for example, was a lot more common already in the early and middle Bronze Age, though not in the context of the later Urnfield culture (e.g. in the Benelux area [@fokkensBronzeAgeLow2013] or Great-Britain [@robertsBritainIrelandBronze2013]). Beyond simple research progress, one additional reason why major misconceptions like this can appear and thrive might be a lack of unified data repositories and universally acknowledged proxies for the distribution of cultural phenomena in European archaeology: Instead of directly querying quantitative data the typical process for the creation of large scale overviews is to excerpt the literature of all relevant local research traditions. The present article in contrast explores whether openly available bulk radiocarbon data could allow to reconstruct the trends within the distribution of burial rites. This could set the precedent for for a more reproducible and statistically sound observation of the main shifts. The quantitative comparison of macroregional trends also paves the way for an analysis of patterns of interaction intensity on a continental scale.  

Already the assumption that the cremation aspect of Early Bronze Age burial rituals in Britain can be directly compared to the same aspect in Hungary requires a theoretical foundation. *Cultural transmission theory* provides a framework where this claim can be explored as a hypothesis for further research. The spread of ideas in human populations over space and time is a major topic of *Cultural evolution theory* [@creanzaCulturalEvolutionaryTheory2017]. This line of thought is as least as old as theories of biological evolution and underwent a long and versatile research history from *Evolutionism* and *Social Darwinism* in the 19th and early 20th century, against *Cultural relativism* and back to *Neoevolutionism* up until the nineteen sixties and seventies [@petermannGeschichteEthnologie2004]. In the late seventies the the discussion took another turn away from social structure to the more general observation of human behaviour. Three major theoretical movements emerged in this context: *Evolutionary psychology*, *Human behavioural ecology* and *Dual inheritance theory* [@smithThreeStylesEvolutionary2000]. The latter -- heavily popularized by Richard Dawkin's *Memetics* [@dawkinsSelfishGene1976] -- establishes the notion of culture acting as secondary heredity system in humans [@henrichDualinheritanceTheoryEvolution2007]. Just like in biological evolution there might be selection and mutation within *Social learning* and therefore methods of *Population genetics* could be employed within cultural anthropology -- of course with the much faster pace of cultural exchange in mind. A lot of theoretical and quantitative research arose from this assumptions: e.g. @cavalli-sforzaCulturalTransmissionEvolution1981, @boydCultureEvolutionaryProcess1985, @teltserEvolutionaryArchaeologyMethodological1995 or @obrienEvolutionaryArchaeologyTheory1996.

Archaeology has a special perspective to offer for Cultural evolution research: It's concerned with questions that can embrace continent size areas and millennia of cultural development [@garveyCurrentPotentialRoles2018]. Archaeological data is mostly comprised of the material remains of human behaviour -- so the ruins of past architecture, individual lost or discarded artefacts and all more inconspicuous by-products of living. We rightfully expect humans to learn handcraft as well as building techniques and traditions  -- both functionally meaningful and seemingly pointless -- from others close to them. The similarity of historically and spatially close material remains can therefore be explained as a result of social interaction [@lymanChronometersUnitsEarly2000; @lymanCultureHistoricalBiological2001; @lymanRiseFallCulture1997; @obrienEpistemologicalNatureArchaeological2002]. In this context a distinction of culture in function and style became an important question for *Evolutionary archaeology*, explicitly elaborated already by @dunnell1978style. Some types of human behaviour obviously increase well-being and simplify survival, like certain hunting techniques, superior tools or sowing more fruitful crops. Without resorting to the inappropriate simplifications of Evolutionism their diffusion can be expected to increase over time. On the other hand there are behaviours that are not obviously related to survival and reproductive capacity, like e.g. ceramic decorations, traditional costume fashion or jewellery design. Despite (or because?) their seemingly secondary importance these characteristics often pass through a breathtakingly fast development and serve archaeologists as proxy for relative chronology. Dunnell postulates that the distribution and emergence of these stylistic cultural traits behave randomly on a population scale level. The stochastic processes that are at work are an important object of investigation and discussed as *Neutral Transmission* or *Stylistic variability* [@bentleyRandomDriftCulture2004; @lipoNeutralityStyleDrift2001; @neimanStylisticVariationEvolutionary1995; @rogersNaturalSelectionCultural2008; @shennanCeramicStyleChange2001]. 

Burial traditions are ritualised behaviour most of the times heavily linked to religious and spiritual beliefs. For this paper they are assumed to be stylistic traits as defined by @dunnell1978style. 



Fraser Neimans Article Stylistic Variation in Evolutionary Perspective: Inferences from Decorative Diversity and Interassemblage Distance in Illinois Woodland Ceramic Assemblages explores the new technologies proposed by Dunnell. stochastic processes and develops a simple framework for the simulation of propagation of non-functional ideas. In the process, the essential phenomena drift and flow (at Neiman: intergroup transmission) from population genetics in archaeology and to the interpretation of the Cultural distances between Indian ceramic inventories is used. Neiman's contribution was well received by the experts. very intensively received. Carl can be called Lipos works on ceramics in the Mississippi underflow, the Cultural Transmission Simulation with classical archaeological seriation, Shennans Investigation of the technological development of linear-band ceramics Ceramics in Merzbachtal or Timothy Kohlers analysis of the diversity of forms and its Role as proxy to the prehistoric social fabric in the southwest of the USA, again with ceramics . Also for the preparation of the simulation of this work was his contribution is an essential inspiration (see chapter 4.3.1). 

Evolutionary Archaeology has - parallel to the further development of the the science of archaeology - in the past 15 years of dynamism. The latest Developments show that they are more successful than almost any other archaeological faculty the scientific and Ideal for gradual, theoretical further development from one contribution to the next. During Neiman the concept of his simulation from population genetics was borrowed from other methodology for the Preparation and investigation of phylogenetic trees from cladistics to archaeological questions applied . Stylistic Variability is a very promising basis for modelling with regard to cultural (in comparison to spatial) distance. The Bayes' theorem has proven to be a potent statistical tool. to the model analysis and evaluation revealed . Archaeological data sets and their special features for Cultural evolution research is becoming more rigorous today. questioned and analysed more consciously - beyond the anecdotal evidence.  
