# Materials and Methods {#materials-and-methods}

The analysis code of this paper is written in the statistics programming language R [@rcoreteamLanguageEnvironmentStatistical2018] and fully reproducible: **doi**. A more in-depth description and discussion of the data preparation can be found in the master thesis this article is based on **TODO**.

The dataset used for the analysis in this paper is a subset of the openly available database Radon-B [@kneiselRadonB2013]. It contains ^14^C dates from the European Bronze and Early Iron Age (2300 BC to 500 BC). Radiocarbon dating is one of the major absolute dating techniques for this period [@ramseyRadiocarbonDatingRevolutions2008] and Radon-B is a collection of more than 11000 published dates from around 2800 sites from all over europe (as of December 2018). Beyond the identifying laboratory number, the actual, uncalibrated date and a literature reference, the ^14^C dates in Radon-B are also documented with context information about the name and location of the dated site (coordinates), the sample material and the the type and cultural attribution of the sampled context. The variable *Feature type* systematically distinguishes for example between settlements, rockshelters and also different kinds of graves: *Grave (cremation), Grave (flat) inhumation*, etc.. This information allows to accurately and precisely determine a moment in space and time, when a grave of a certain type was created. In theory the more radiocarbon dates with this information are available, the better becomes our understanding and reconstruction of burial traditions in prehistoric Europe. Unfortunately the Radon-B dataset has some quality issues mostly due to inconsistent manual data input: Incompleteness and faultiness of meta information, no supervised or well thought-out variable classification for *sample material* and *cultural attribution* and inconsistent multilingualism even within individual entries. These issues though do not inhibit the general data analysis strategy of this paper.

To create a tidy and useful subset of Radon-B, the following major steps of data preparation were applied. Please see the code for details of implementation. The value in brackets indicates the number of dates still available after the respective filtering operation.

1. Downloading the Radon-B dataset with the R package c14bazAAR [@schmidC14bazAARDownloadPrepare2018], which allows to access several open radiocarbon archives. (11048 dates)

2. Removing all dates without age information or age information outside of the limits of the Intcal13 calibration curve: 71 - 46401 BP [@reimer_intcal13_2013]. (10956 dates)

3. Calibrating the ^14^C dates with the R package Bchron [@haslettSimpleMonotoneProcess2008], which implements the calibration algorithm with numerical integration.

4. Reducing date selection to all dates whose $2\sigma$ calibrated age range overlap by at least one year with the predefined window of interest: 2200 -- 800 calBC. (7543 dates)

5. Reducing the date selection to all dates taken from graves as indicated by the *Feature type* variable. (2361)

6. Transforming the variable *Feature type* via pattern matching to two new variables *burial type* (inhumation/cremation/unknown) and *burial construction* (mound/flat/unknown).

7. Manually defining a rectangular (EPSG:102013) research area with sufficient information in Central-, Northern and Northwestern Europe based on perceived spatial date distribution (Figure **TODO**).

8. Reducing date selection to dates within the research area. (1894 dates)

9. Removing ^14^C date doubles with tools of c14bazAAR. (1848 dates)

10. Transforming data from the meaning *^14^C dates on graves* to *burial type at a certain time*. For 498 entries in the thus far assembled subset the attribution to *site* and *feature* is not unique. That means that for many graves multiple (up to 8) ^14^C dates have been created and entered in Radon-B. Dates can't be treated as semantically equal to graves. There's a variety of phenomena that cause this effect: In some cases safety measurements were taken -- multiple dates for one single grave that all fall within the margin of errors of each other. In other cases there is a set of strongly diverging dates for a collective grave that was used for hundreds of years. There are also cases where the *feature* information in the database is not sufficient to determine whether two dates are really from the same grave despite the identical entry. The following subalgorithm was applied to solve the problem automatically. This approach is compatible with the intention to create a cultural trait timeseries as explained below. (1704 graves)

    1. If for an individual ^14^C date no numbers appear in it's *feature* variable value, than it is treaded as an individual grave.
    
    2. For the remaining 252 problematic cases, groups were created by *site* and *feature*. The cummulated timespan covered by the $2\sigma$ age range of all these dates where taken as the relevant timespan for the respective grave.

11. Defining macroregions to observe the development of *burial type* and *burial construction* within sensible geographical and cultural units that are appropriate to the amount of available data. The regions are circular and were delimited semiautomatically by creating a regular grid in accordance to main cultural-historical regions of the european Bronze Age (**citation**). The regions have a radius of 240km and overlap slightly (Figure **TODO**). That means some graves are counted towards not just one but two regions.

12. Reducing the date selection to the space covered by the macroregions and attributing the dates to the respective units. (1562 graves)

The resulting dataset contains **TODO**

This data for individual graves attributed to a macroregion can be transformed to a timeseries of trait prevalence within the respective regions during the the timeframe of interest. The first step is to create a absolute occurence time series **TODO**

The continous timeseries of yearwise burial rite proportions for each region allow to calculate timeseries of a measure of cultural distance for each region relation (Figure **TODO**). Several different measures of cultural distance could be used here following the discussion of these matters in the relevant literature (**TODO**). In this context the Squared Euclidian Distance (SED) seems to be a sensible statistic, because it is fairly simple, works with only few assumptions and emphasizes differences through squaring.

The SED is defined here as:

$$d_{ij}^2 = \sum_{k = 1}^{n} (p_{ik} - p_{jk})^2$$

- $d_{ij}^2$: SED between tqo groups $i$ and $j$

- $k$: trait counter 

- $n$: number of traits in the population

- $p_{ik}$: relative frequency of the $k$th trait in group $i$

- $p_{jk}$: relative frequency of the $k$th trait in group $j$

To test for correlation between the distances based on the variables *burial type* and *burial construction*, the timeframe of interest was devided into sections of 200 years. For each section of each the two variables, a matrix of the mean SED over time was calculated. The two matrizes of each section can be tested for correlation with the Mantel test, which **TODO** [@mantelDetectionDiseaseClustering1967]. Since both distances compared here, *burial type* and *burial construction* distance, are cardinal scale variables, the Pearson correlation coefficient [@pearsonNotesRegressionInheritance1895] can be applied as a base measure for the Mantel test. The mean correlation for each of the $\frac{8*8}{2}-\frac{8}{2}=28$ region-region relations can be plotted in the *burial type*SED-*burial construction*SED space (Figure **TODO**).

Defining a measure of spatial distance for the above established main units of observation, the macroregions, is only possible in a highly simplified way. A contionus distance measure can't be employed, but it's possible to distinguish ordinal distance classes. For the eight regions four different categories of spatial distance were defined. The test for correlation between spatial and cultural distance works similar to the one between the two cultural distances above, except that the Mantel test has to be applied with Spearman's rank correlation coefficient [@spearmanProofMeasurementAssociation1904] here, because of the difference in the data level of measurements (Figure **TODO**). 

To get a better understanding how the correlation coefficient should develop if there were strong correlation between spatial and cultural distance as measured by *burial type* and *burial construction*, a simple simulation was implemented based on the model proposed by @neimanStylisticVariationEvolutionary1995. This simulation assumes a population separated into $g$ groups with a group population of $N_g$ each. At the beginning of the simulation there are $k$ ideas randomly, but equally distributed in this population. With every timestep -- $t$ defines the total number of timesteps -- all individuals learn from an other randomly chosen individual. The probability that this other individual is from an other group equals $m_i$, for the opposite therefore $1-m_i$. The partner group for each individual learning instance is selected randomly following a group interaction probability defined in the matrix $I$. The distribution of the $k$ variants can be observed for every timestep and documented in a timeseries like the one for real world data (Figure **TODO**).

For the actual simulation runs, the parameters were chosen as follows: **TODO**
