# Discussion {#discussion}

- Comparison archaeological observations and reconstruction based on data  

- Surprising result of no correlation: Meaning? Construction of an own story?

- General and concluding observations

In reality, beyond Dunnels distinction, most behaviour is not unambiguously stylistic or functional. For the sake of this case study burial rites are assumed to be stylistic, but in fact their creation causes costs in terms of working time and material to a varying extent. This cost might have been influenced or had their own effect on the human-nature relation: Pyres for example require a significant amount of wood and the erection of barrows several days of manpower. Still it can be expected that these functional disadvantages weren't critical most of the time for the general decision which kind of burial tradition is applied, but maybe for the magnitude of invested energy. Other factors to consider here are the level of grief [@macdonaldGriefBurialAmerican2001] or the representational intentions of the burying relatives [@henrichEvolutionCostlyDisplays2009].
