# Travis (travis-ci.com) is not active any more,
# but it was used for continous rendering of the
# article during its preparation.

language: r

cache:
  packages: yes

sudo: required

env:
  global:
    - secure: "12345"

# blocklist
branches:
  except:
  - document

addons:
  apt:
    packages:
      - pandoc-citeproc

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

before_script:
  - chmod +x ./_run_analysis.sh
  - chmod +x ./_render_article.sh
  - chmod +x ./_deploy_article.sh

script:
  - travis_wait 30 ./_run_analysis.sh
  - ./_copy_and_render.sh
  - ./_deploy_article.sh

